version: 2
updates:
- package-ecosystem: helm
  directory: "/charts"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/.github/workflows"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
